<h1 style="color: #F70206; text-shadow: 2px 2px 4px #000000; border: 1px solid #000000; font-size: 60px; text-align: center; background-color: #A1A1A3;"> üèéÔ∏è FORMULA 1: LAP TIMES üèéÔ∏è </h1>

<h1 style="color: #F70206; text-shadow: 2px 2px 4px #000000; border: 1px solid #000000; font-size: 36px;">00 | First Steps </h1>

In [1]:
import pandas as pd                                      # üòÄ Importa la biblioteca pandas y la renombra como pd para su uso en el c√≥digo.
import matplotlib.pyplot as plt                          # üìä Importa la biblioteca matplotlib.pyplot y la renombra como plt para su uso en el c√≥digo.
import seaborn as sns                                    # üìà Importa la biblioteca seaborn para gr√°ficos estad√≠sticos.
import numpy as np                                       # üî¢ Importa la biblioteca numpy y la renombra como np para su uso en el c√≥digo.
from scipy.stats import chi2_contingency                 # üìä Importa la funci√≥n chi2_contingency de la biblioteca scipy.stats para realizar pruebas de independencia.
from scipy.stats.contingency import association          # üìä Importa la funci√≥n association de la biblioteca scipy.stats.contingency para calcular medidas de asociaci√≥n en tablas de contingencia.
import statsmodels.api as sm                             # üìà Importa la biblioteca statsmodels.api para an√°lisis estad√≠stico y modelado.
import scipy.stats as st                                 # üî¨ Importa la biblioteca scipy.stats para distribuciones y pruebas estad√≠sticas.
from sklearn.model_selection import train_test_split     # üõ†Ô∏è Importa la funci√≥n train_test_split de la biblioteca sklearn.model_selection para dividir datos en conjuntos de entrenamiento y prueba.
from sklearn.linear_model import LinearRegression        # üìà Importa el modelo de regresi√≥n lineal de la biblioteca sklearn.linear_model.
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error  # üìä Importa m√©tricas de evaluaci√≥n de modelos de la biblioteca sklearn.metrics.
from sklearn.linear_model import Ridge                   # üìà Importa el modelo de regresi√≥n Ridge de la biblioteca sklearn.linear_model.
from sklearn.linear_model import Lasso                   # üìà Importa el modelo de regresi√≥n Lasso de la biblioteca sklearn.linear_model.
from sklearn.tree import DecisionTreeRegressor           # üå≥ Importa el modelo de regresi√≥n de √°rbol de decisi√≥n de la biblioteca sklearn.tree.
from sklearn.neighbors import KNeighborsRegressor        # üè† Importa el modelo de regresi√≥n de vecinos m√°s cercanos de la biblioteca sklearn.neighbors.
from sklearn.preprocessing import MinMaxScaler           # üìè Importa la clase MinMaxScaler de la biblioteca sklearn.preprocessing para escalar caracter√≠sticas al rango [0, 1].
from sklearn.preprocessing import StandardScaler         # üìè Importa la clase StandardScaler de la biblioteca sklearn.preprocessing para estandarizar caracter√≠sticas eliminando la media y escalando a la varianza unitaria.
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.utils import resample
import xgboost as xgb                                    # üöÄ Importa la biblioteca xgboost para el modelado de gradient boosting.
import warnings                                          # ‚ö†Ô∏è Importa la biblioteca warnings para manejar advertencias.
from datetime import datetime                            # üìÖ Importa la clase datetime de la biblioteca datetime para trabajar con fechas y horas.
from sklearn import preprocessing                        # üõ†Ô∏è Importa el m√≥dulo preprocessing de la biblioteca sklearn para realizar preprocesamiento de datos.

<div class="alert alert-block alert-info" style="background-color: rgba(247, 2, 6, 0.2); color: black;">
    <strong>Tip #1</strong> RELLENAR!
</div>

<h4 style="color: #F70206;">Other settings</h4>

In [2]:
warnings.filterwarnings("ignore")
%matplotlib inline
pd.set_option('display.max_columns', None)

<h4 style="color: #F70206;">Data Extraction</h4>

In [3]:
data1 = pd.read_csv("df1_bahrain_q1_predicted.csv")
data2 = pd.read_csv("dfq2.csv")

<h4 style="color: #F70206;">Exploring the Data (First Impression)</h4>

In [4]:
df1 = data1.copy()
df2 = data2.copy()

<h4 style="color: #F70206;">DF PREPARATION</h4>

In [5]:
df1

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,car_condition,driver_condition,position_q1,previous_year_position_q1,circuitref_fastlap,driver_time_vs_fastlap,car_time_vs_fastlap,previous_driver_time_vs_fastlap,previous_car_time_vs_fastlap,q1
0,8735.0,1052,830.0,9.0,1.0,2021.0,1.0,3.0,bahrain,0.00,0.0,1.0,20.0,89708.0,791.0,1124.0,0.0,0.0,90499.000
1,8745.0,1052,815.0,9.0,10.0,2021.0,1.0,3.0,bahrain,0.00,0.0,10.0,20.0,89708.0,1457.0,1124.0,0.0,0.0,91165.000
2,8747.0,1052,852.0,213.0,2.0,2021.0,1.0,3.0,bahrain,0.00,0.0,2.0,20.0,89708.0,899.0,1019.5,0.0,0.0,90607.000
3,8739.0,1052,842.0,213.0,6.0,2021.0,1.0,3.0,bahrain,0.00,0.0,6.0,20.0,89708.0,1140.0,1019.5,0.0,0.0,90848.000
4,8736.0,1052,1.0,131.0,3.0,2021.0,1.0,3.0,bahrain,0.00,0.0,3.0,20.0,89708.0,909.0,1200.5,0.0,0.0,90617.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,9883.0,1111,842.0,214.0,0.0,2024.0,1.0,3.0,bahrain,20.00,0.0,20.0,20.0,89708.0,NaN,NaN,-2473.0,-2136.5,92144.375
76,9884.0,1111,839.0,214.0,0.0,2024.0,1.0,3.0,bahrain,20.00,40.0,17.0,12.0,89708.0,NaN,NaN,-1800.0,-2136.5,92120.900
77,9887.0,1111,825.0,210.0,0.0,2024.0,1.0,3.0,bahrain,7.50,15.0,5.0,17.0,89708.0,NaN,NaN,-2184.0,-1840.0,92071.500
78,9888.0,1111,848.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,55.0,7.0,9.0,89708.0,NaN,NaN,-1753.0,-1848.5,92093.260
79,9890.0,1111,858.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,22.5,15.0,15.5,89708.0,NaN,NaN,-1944.0,-1848.5,92116.150

In [6]:
df2 = df2[df2["circuitref"] == "bahrain"]
df2

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,q2
20,8735,1052,830,9,1,2021,1,3,bahrain,90318.0
21,8754,1052,853,210,20,2021,1,3,bahrain,0.0
22,8738,1052,844,6,4,2021,1,3,bahrain,90010.0
23,8739,1052,842,213,5,2021,1,3,bahrain,90513.0
24,8740,1052,817,1,6,2021,1,3,bahrain,90222.0
25,8741,1052,846,1,7,2021,1,3,bahrain,90099.0
26,8742,1052,832,6,8,2021,1,3,bahrain,90009.0
27,8743,1052,4,214,9,2021,1,3,bahrain,90595.0
28,8744,1052,840,117,10,2021,1,3,bahrain,90624.0
29,8745,1052,815,9,11,2021,1,3,bahrain,90659.0
30,8746,1052,841,51,12,2021,1,3,bahrain,90708.0
31,8747,1052,852,213,13,2021,1,3,bahrain,91203.0
32,8748,1052,8,51,14,2021,1,3,bahrain,91238.0
33,8749,1052,847,3,15,2021,1,3,bahrain,93430.0
34,8750,1052,839,214,16,2021,1,3,bahrain,0.0
35,8751,1052,849,3,17,2021,1,3,bahrain,0.0
36,8752,1052,20,117,18,2021,1,3,bahrain,0.0
37,8753,1052,854,210,19,2021,1,3,bahrain,0.0
38,8737,1052,822,131,3,2021,1,3,bahrain,90186.0
39,8736,1052,1,131,2,2021,1,3,bahrain,90085.0
439,9187,1074,854,210,12,2022,1,3,bahrain,91998.0
440,9194,1074,840,117,19,2022,1,3,bahrain,0.0
441,9193,1074,817,1,18,2022,1,3,bahrain,0.0
442,9192,1074,807,117,17,2022,1,3,bahrain,0.0
443,9191,1074,852,213,16,2022,1,3,bahrain,0.0
444,9190,1074,855,51,15,2022,1,3,bahrain,93543.0
445,9189,1074,848,3,14,2022,1,3,bahrain,92664.0
446,9188,1074,846,1,13,2022,1,3,bahrain,92008.0
447,9186,1074,839,214,11,2022,1,3,bahrain,91782.0
448,9195,1074,849,3,20,2022,1,3,bahrain,0.0
449,9184,1074,847,131,9,2022,1,3,bahrain,91252.0
450,9176,1074,844,6,1,2022,1,3,bahrain,90932.0
451,9177,1074,830,9,2,2022,1,3,bahrain,90757.0
452,9178,1074,832,6,3,2022,1,3,bahrain,90787.0
453,9179,1074,815,9,4,2022,1,3,bahrain,91008.0
454,9185,1074,842,213,10,2022,1,3,bahrain,91635.0
455,9181,1074,822,51,6,2022,1,3,bahrain,91717.0
456,9182,1074,825,210,7,2022,1,3,bahrain,91461.0
457,9183,1074,4,214,8,2022,1,3,bahrain,91621.0
458,9180,1074,1,131,5,2022,1,3,bahrain,91048.0
879,9645,1098,855,51,13,2023,1,3,bahrain,91473.0
880,9652,1098,842,214,20,2023,1,3,bahrain,0.0
881,9651,1098,856,213,19,2023,1,3,bahrain,0.0
882,9650,1098,857,1,18,2023,1,3,bahrain,0.0
883,9649,1098,825,210,17,2023,1,3,bahrain,0.0
884,9648,1098,858,3,16,2023,1,3,bahrain,0.0
885,9647,1098,848,3,15,2023,1,3,bahrain,0.0
886,9646,1098,852,213,14,2023,1,3,bahrain,92510.0
887,9644,1098,822,51,12,2023,1,3,bahrain,91443.0
888,9643,1098,846,1,11,2023,1,3,bahrain,91381.0
889,9633,1098,830,9,1,2023,1,3,bahrain,90503.0
890,9634,1098,815,9,2,2023,1,3,bahrain,90746.0
891,9635,1098,844,6,3,2023,1,3,bahrain,90282.0
892,9636,1098,832,6,4,2023,1,3,bahrain,90515.0
893,9637,1098,4,117,5,2023,1,3,bahrain,90645.0
894,9642,1098,807,210,10,2023,1,3,bahrain,90809.0
895,9639,1098,1,131,7,2023,1,3,bahrain,90513.0
896,9640,1098,840,117,8,2023,1,3,bahrain,91127.0
897,9641,1098,839,214,9,2023,1,3,bahrain,90914.0
898,9638,1098,847,131,6,2023,1,3,bahrain,90507.0

In [7]:
df1 = df1.sort_values(by=['year', 'driverid'], ascending=[True, True])
df2 = df2.sort_values(by=['year', 'driverid'], ascending=[True, True])

In [8]:
# Suponiendo que 'driverid' y 'year' sean las columnas comunes entre df1 y df2
df1 = pd.merge(df1, df2[['driverid', 'year', 'q2']], on=['driverid', 'year'], how='left')

In [9]:
df1.head(60).sort_values(by=["year", "q1"], ascending=[True, True])

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,car_condition,driver_condition,position_q1,previous_year_position_q1,circuitref_fastlap,driver_time_vs_fastlap,car_time_vs_fastlap,previous_driver_time_vs_fastlap,previous_car_time_vs_fastlap,q1,q2
7,8735.0,1052,830.0,9.0,1.0,2021.0,1.0,3.0,bahrain,0.0,0.0,1.0,20.0,89708.0,791.0,1124.0,0.0,0.0,90499.0,90318.0
17,8747.0,1052,852.0,213.0,2.0,2021.0,1.0,3.0,bahrain,0.0,0.0,2.0,20.0,89708.0,899.0,1019.5,0.0,0.0,90607.0,91203.0
0,8736.0,1052,1.0,131.0,3.0,2021.0,1.0,3.0,bahrain,0.0,0.0,3.0,20.0,89708.0,909.0,1200.5,0.0,0.0,90617.0,90085.0
13,8738.0,1052,844.0,6.0,4.0,2021.0,1.0,3.0,bahrain,0.0,0.0,4.0,20.0,89708.0,983.0,1464.0,0.0,0.0,90691.0,90010.0
5,8740.0,1052,817.0,1.0,5.0,2021.0,1.0,3.0,bahrain,0.0,0.0,5.0,20.0,89708.0,1087.0,1140.5,0.0,0.0,90795.0,90222.0
12,8739.0,1052,842.0,213.0,6.0,2021.0,1.0,3.0,bahrain,0.0,0.0,6.0,20.0,89708.0,1140.0,1019.5,0.0,0.0,90848.0,90513.0
1,8743.0,1052,4.0,214.0,7.0,2021.0,1.0,3.0,bahrain,0.0,0.0,7.0,20.0,89708.0,1155.0,1585.5,0.0,0.0,90863.0,90595.0
14,8741.0,1052,846.0,1.0,8.0,2021.0,1.0,3.0,bahrain,0.0,0.0,8.0,20.0,89708.0,1194.0,1140.5,0.0,0.0,90902.0,90099.0
11,8746.0,1052,841.0,51.0,9.0,2021.0,1.0,3.0,bahrain,0.0,0.0,9.0,20.0,89708.0,1290.0,1564.5,0.0,0.0,90998.0,90708.0
4,8745.0,1052,815.0,9.0,10.0,2021.0,1.0,3.0,bahrain,0.0,0.0,10.0,20.0,89708.0,1457.0,1124.0,0.0,0.0,91165.0,90659.0
6,8737.0,1052,822.0,131.0,11.0,2021.0,1.0,3.0,bahrain,0.0,0.0,11.0,20.0,89708.0,1492.0,1200.5,0.0,0.0,91200.0,90186.0
10,8744.0,1052,840.0,117.0,12.0,2021.0,1.0,3.0,bahrain,0.0,0.0,12.0,20.0,89708.0,1553.0,1950.5,0.0,0.0,91261.0,90624.0
15,8749.0,1052,847.0,3.0,13.0,2021.0,1.0,3.0,bahrain,0.0,0.0,13.0,20.0,89708.0,1608.0,1918.0,0.0,0.0,91316.0,93430.0
2,8748.0,1052,8.0,51.0,14.0,2021.0,1.0,3.0,bahrain,0.0,0.0,14.0,20.0,89708.0,1839.0,1564.5,0.0,0.0,91547.0,91238.0
8,8742.0,1052,832.0,6.0,15.0,2021.0,1.0,3.0,bahrain,0.0,0.0,15.0,20.0,89708.0,1945.0,1464.0,0.0,0.0,91653.0,90009.0
9,8750.0,1052,839.0,214.0,16.0,2021.0,1.0,3.0,bahrain,0.0,0.0,16.0,20.0,89708.0,2016.0,1585.5,0.0,0.0,91724.0,0.0
16,8751.0,1052,849.0,3.0,17.0,2021.0,1.0,3.0,bahrain,0.0,0.0,17.0,20.0,89708.0,2228.0,1918.0,0.0,0.0,91936.0,0.0
3,8752.0,1052,20.0,117.0,18.0,2021.0,1.0,3.0,bahrain,0.0,0.0,18.0,20.0,89708.0,2348.0,1950.5,0.0,0.0,92056.0,0.0
19,8753.0,1052,854.0,210.0,19.0,2021.0,1.0,3.0,bahrain,0.0,0.0,19.0,20.0,89708.0,2741.0,3153.0,0.0,0.0,92449.0,0.0
18,8754.0,1052,853.0,210.0,20.0,2021.0,1.0,3.0,bahrain,0.0,0.0,20.0,20.0,89708.0,3565.0,3153.0,0.0,0.0,93273.0,0.0
32,9176.0,1074,844.0,6.0,1.0,2022.0,1.0,3.0,bahrain,52.5,80.0,1.0,4.0,89708.0,1763.0,1811.0,-983.0,-1464.0,91471.0,90932.0
28,9178.0,1074,832.0,6.0,2.0,2022.0,1.0,3.0,bahrain,52.5,25.0,2.0,15.0,89708.0,1859.0,1811.0,-1945.0,-1464.0,91567.0,90787.0
27,9177.0,1074,830.0,9.0,3.0,2022.0,1.0,3.0,bahrain,72.5,95.0,3.0,1.0,89708.0,2077.0,2340.0,-791.0,-1124.0,91785.0,90757.0
25,9181.0,1074,822.0,51.0,4.0,2022.0,1.0,3.0,bahrain,22.5,45.0,4.0,11.0,89708.0,2211.0,2498.0,-1492.0,-1200.5,91919.0,91717.0
26,9182.0,1074,825.0,210.0,5.0,2022.0,1.0,3.0,bahrain,2.5,0.0,5.0,20.0,89708.0,2247.0,2459.5,0.0,0.0,91955.0,91461.0
29,9186.0,1074,839.0,214.0,6.0,2022.0,1.0,3.0,bahrain,42.5,20.0,6.0,16.0,89708.0,2333.0,2485.5,-2016.0,-1585.5,92041.0,91782.0
31,9185.0,1074,842.0,213.0,7.0,2022.0,1.0,3.0,bahrain,80.0,70.0,7.0,6.0,89708.0,2388.0,2715.0,-1140.0,-1019.5,92096.0,91635.0
33,9188.0,1074,846.0,1.0,8.0,2022.0,1.0,3.0,bahrain,67.5,60.0,8.0,8.0,89708.0,2531.0,2884.0,-1194.0,-1140.5,92239.0,92008.0
34,9184.0,1074,847.0,131.0,9.0,2022.0,1.0,3.0,bahrain,60.0,35.0,9.0,13.0,89708.0,2561.0,2569.0,-1608.0,-1918.0,92269.0,91252.0
20,9180.0,1074,1.0,131.0,10.0,2022.0,1.0,3.0,bahrain,60.0,85.0,10.0,3.0,89708.0,2577.0,2569.0,-909.0,-1200.5,92285.0,91048.0
23,9179.0,1074,815.0,9.0,11.0,2022.0,1.0,3.0,bahrain,72.5,50.0,11.0,10.0,89708.0,2603.0,2340.0,-1457.0,-1124.0,92311.0,91008.0
21,9183.0,1074,4.0,214.0,12.0,2022.0,1.0,3.0,bahrain,42.5,65.0,12.0,7.0,89708.0,2638.0,2485.5,-1155.0,-1585.5,92346.0,91621.0
38,9187.0,1074,854.0,210.0,13.0,2022.0,1.0,3.0,bahrain,2.5,5.0,13.0,19.0,89708.0,2672.0,2459.5,-2741.0,-3153.0,92380.0,91998.0
39,9190.0,1074,855.0,51.0,14.0,2022.0,1.0,3.0,bahrain,22.5,0.0,14.0,20.0,89708.0,2785.0,2498.0,0.0,0.0,92493.0,93543.0
35,9189.0,1074,848.0,3.0,15.0,2022.0,1.0,3.0,bahrain,7.5,0.0,15.0,20.0,89708.0,3018.0,3472.0,0.0,0.0,92726.0,92664.0
37,9191.0,1074,852.0,213.0,16.0,2022.0,1.0,3.0,bahrain,80.0,90.0,16.0,2.0,89708.0,3042.0,2715.0,-899.0,-1019.5,92750.0,0.0
22,9192.0,1074,807.0,117.0,17.0,2022.0,1.0,3.0,bahrain,20.0,0.0,17.0,20.0,89708.0,3069.0,3196.5,0.0,0.0,92777.0,0.0
24,9193.0,1074,817.0,1.0,18.0,2022.0,1.0,3.0,bahrain,67.5,75.0,18.0,5.0,89708.0,3237.0,2884.0,-1087.0,-1140.5,92945.0,0.0
30,9194.0,1074,840.0,117.0,19.0,2022.0,1.0,3.0,bahrain,20.0,40.0,19.0,12.0,89708.0,3324.0,3196.5,-1553.0,-1950.5,93032.0,0.0
36,9195.0,1074,849.0,3.0,20.0,2022.0,1.0,3.0,bahrain,7.5,15.0,20.0,17.0,89708.0,3926.0,3472.0,-2228.0,-1918.0,93634.0,0.0
47,9636.0,1098,832.0,6.0,1.0,2023.0,1.0,3.0,bahrain,92.5,90.0,1.0,2.0,89708.0,1285.0,1335.5,-1859.0,-1811.0,90993.0,90515.0
53,9638.0,1098,847.0,131.0,2.0,2023.0,1.0,3.0,bahrain,52.5,55.0,2.0,9.0,89708.0,1349.0,1592.0,-2561.0,-2569.0,91057.0,90507.0
51,9635.0,1098,844.0,6.0,3.0,2023.0,1.0,3.0,bahrain,92.5,95.0,3.0,1.0,89708.0,1386.0,1335.5,-1763.0,-1811.0,91094.0,90282.0
41,9637.0,1098,4.0,117.0,4.0,2023.0,1.0,3.0,bahrain,22.5,40.0,4.0,12.0,89708.0,1450.0,1463.0,-2638.0,-2485.5,91158.0,90645.0
49,9640.0,1098,840.0,117.0,5.0,2023.0,1.0,3.0,bahrain,22.5,5.0,5.0,19.0,89708.0,1476.0,1463.0,-3324.0,-3196.5,91184.0,91127.0
42,9642.0,1098,807.0,210.0,6.0,2023.0,1.0,3.0,bahrain,45.0,15.0,6.0,17.0,89708.0,1496.0,1840.0,-3069.0,-3196.5,91204.0,90809.0
46,9633.0,1098,830.0,9.0,7.0,2023.0,1.0,3.0,bahrain,65.0,85.0,7.0,3.0,89708.0,1587.0,1679.0,-2077.0,-2340.0,91295.0,90503.0
55,9646.0,1098,852.0,213.0,8.0,2023.0,1.0,3.0,bahrain,10.0,20.0,8.0,16.0,89708.0,1692.0,2052.5,-3042.0,-2715.0,91400.0,92510.0
54,9647.0,1098,848.0,3.0,9.0,2023.0,1.0,3.0,bahrain,12.5,25.0,9.0,15.0,89708.0,1753.0,1848.5,-3018.0,-3472.0,91461.0,0.0
43,9634.0,1098,815.0,9.0,10.0,2023.0,1.0,3.0,bahrain,65.0,45.0,10.0,11.0,89708.0,1771.0,1679.0,-2603.0,-2340.0,91479.0,90746.0
44,9644.0,1098,822.0,51.0,11.0,2023.0,1.0,3.0,bahrain,55.0,80.0,11.0,4.0,89708.0,1796.0,1851.5,-2211.0,-2498.0,91504.0,91443.0
48,9641.0,1098,839.0,214.0,12.0,2023.0,1.0,3.0,bahrain,67.5,70.0,12.0,6.0,89708.0,1800.0,2136.5,-2333.0,-2485.5,91508.0,90914.0
40,9639.0,1098,1.0,131.0,13.0,2023.0,1.0,3.0,bahrain,52.5,50.0,13.0,10.0,89708.0,1835.0,1592.0,-2577.0,-2569.0,91543.0,90513.0
56,9645.0,1098,855.0,51.0,14.0,2023.0,1.0,3.0,bahrain,55.0,30.0,14.0,14.0,89708.0,1907.0,1851.5,-2785.0,-2498.0,91615.0,91473.0
52,9643.0,1098,846.0,1.0,16.0,2023.0,1.0,3.0,bahrain,30.0,60.0,15.5,8.0,89708.0,1944.0,2168.5,-2531.0,-2884.0,91652.0,91381.0
59,9648.0,1098,858.0,3.0,15.0,2023.0,1.0,3.0,bahrain,12.5,0.0,15.5,20.0,89708.0,1944.0,1848.5,0.0,0.0,91652.0,0.0
45,9649.0,1098,825.0,210.0,17.0,2023.0,1.0,3.0,bahrain,45.0,75.0,17.0,5.0,89708.0,2184.0,1840.0,-2247.0,-2459.5,91892.0,0.0
58,9650.0,1098,857.0,1.0,18.0,2023.0,1.0,3.0,bahrain,30.0,0.0,18.0,20.0,89708.0,2393.0,2168.5,0.0,0.0,92101.0,0.0
57,9651.0,1098,856.0,213.0,19.0,2023.0,1.0,3.0,bahrain,10.0,0.0,19.0,20.0,89708.0,2413.0,2052.5,0.0,0.0,92121.0,0.0
50,9652.0,1098,842.0,214.0,20.0,2023.0,1.0,3.0,bahrain,67.5,65.0,20.0,7.0,89708.0,2473.0,2136.5,-2388.0,-2715.0,92181.0,0.0

In [10]:
df1['q2disqualified'] = (df1['position_q1'] > 15) * 1
df1

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,car_condition,driver_condition,position_q1,previous_year_position_q1,circuitref_fastlap,driver_time_vs_fastlap,car_time_vs_fastlap,previous_driver_time_vs_fastlap,previous_car_time_vs_fastlap,q1,q2,q2disqualified
0,8736.0,1052,1.0,131.0,3.0,2021.0,1.0,3.0,bahrain,0.00,0.0,3.0,20.0,89708.0,909.0,1200.5,0.0,0.0,90617.00,90085.0,0
1,8743.0,1052,4.0,214.0,7.0,2021.0,1.0,3.0,bahrain,0.00,0.0,7.0,20.0,89708.0,1155.0,1585.5,0.0,0.0,90863.00,90595.0,0
2,8748.0,1052,8.0,51.0,14.0,2021.0,1.0,3.0,bahrain,0.00,0.0,14.0,20.0,89708.0,1839.0,1564.5,0.0,0.0,91547.00,91238.0,0
3,8752.0,1052,20.0,117.0,18.0,2021.0,1.0,3.0,bahrain,0.00,0.0,18.0,20.0,89708.0,2348.0,1950.5,0.0,0.0,92056.00,0.0,1
4,8745.0,1052,815.0,9.0,10.0,2021.0,1.0,3.0,bahrain,0.00,0.0,10.0,20.0,89708.0,1457.0,1124.0,0.0,0.0,91165.00,90659.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,9888.0,1111,848.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,55.0,7.0,9.0,89708.0,NaN,NaN,-1753.0,-1848.5,92093.26,NaN,0
76,9881.0,1111,852.0,213.0,0.0,2024.0,1.0,3.0,bahrain,70.00,60.0,10.0,8.0,89708.0,NaN,NaN,-1692.0,-2052.5,92103.46,NaN,0
77,9889.0,1111,855.0,51.0,0.0,2024.0,1.0,3.0,bahrain,37.50,30.0,8.0,14.0,89708.0,NaN,NaN,-1907.0,-1851.5,92098.15,NaN,0
78,9878.0,1111,857.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,10.0,16.0,18.0,89708.0,NaN,NaN,-2393.0,-2168.5,92117.37,NaN,1
79,9890.0,1111,858.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,22.5,15.0,15.5,89708.0,NaN,NaN,-1944.0,-1848.5,92116.15,NaN,0

In [11]:
df1["driver_q2vsq1"] = df1["q2"] - df1["q1"]
df1.loc[df1["q2"] == 0, "driver_q2vsq1"] = 0
df1

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,car_condition,driver_condition,position_q1,previous_year_position_q1,circuitref_fastlap,driver_time_vs_fastlap,car_time_vs_fastlap,previous_driver_time_vs_fastlap,previous_car_time_vs_fastlap,q1,q2,q2disqualified,driver_q2vsq1
0,8736.0,1052,1.0,131.0,3.0,2021.0,1.0,3.0,bahrain,0.00,0.0,3.0,20.0,89708.0,909.0,1200.5,0.0,0.0,90617.00,90085.0,0,-532.0
1,8743.0,1052,4.0,214.0,7.0,2021.0,1.0,3.0,bahrain,0.00,0.0,7.0,20.0,89708.0,1155.0,1585.5,0.0,0.0,90863.00,90595.0,0,-268.0
2,8748.0,1052,8.0,51.0,14.0,2021.0,1.0,3.0,bahrain,0.00,0.0,14.0,20.0,89708.0,1839.0,1564.5,0.0,0.0,91547.00,91238.0,0,-309.0
3,8752.0,1052,20.0,117.0,18.0,2021.0,1.0,3.0,bahrain,0.00,0.0,18.0,20.0,89708.0,2348.0,1950.5,0.0,0.0,92056.00,0.0,1,0.0
4,8745.0,1052,815.0,9.0,10.0,2021.0,1.0,3.0,bahrain,0.00,0.0,10.0,20.0,89708.0,1457.0,1124.0,0.0,0.0,91165.00,90659.0,0,-506.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,9888.0,1111,848.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,55.0,7.0,9.0,89708.0,NaN,NaN,-1753.0,-1848.5,92093.26,NaN,0,NaN
76,9881.0,1111,852.0,213.0,0.0,2024.0,1.0,3.0,bahrain,70.00,60.0,10.0,8.0,89708.0,NaN,NaN,-1692.0,-2052.5,92103.46,NaN,0,NaN
77,9889.0,1111,855.0,51.0,0.0,2024.0,1.0,3.0,bahrain,37.50,30.0,8.0,14.0,89708.0,NaN,NaN,-1907.0,-1851.5,92098.15,NaN,0,NaN
78,9878.0,1111,857.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,10.0,16.0,18.0,89708.0,NaN,NaN,-2393.0,-2168.5,92117.37,NaN,1,NaN
79,9890.0,1111,858.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,22.5,15.0,15.5,89708.0,NaN,NaN,-1944.0,-1848.5,92116.15,NaN,0,NaN

In [12]:
car_q2vsq1 = df1.groupby(['constructorid', "year", 'circuitref'])['driver_q2vsq1'].mean()
car_q2vsq1 = car_q2vsq1.reset_index()
df1 = pd.merge(df1, car_q2vsq1, on=['constructorid', "year", 'circuitref'])
df1

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,car_condition,driver_condition,position_q1,previous_year_position_q1,circuitref_fastlap,driver_time_vs_fastlap,car_time_vs_fastlap,previous_driver_time_vs_fastlap,previous_car_time_vs_fastlap,q1,q2,q2disqualified,driver_q2vsq1_x,driver_q2vsq1_y
0,8736.0,1052,1.0,131.0,3.0,2021.0,1.0,3.0,bahrain,0.00,0.0,3.0,20.0,89708.0,909.0,1200.5,0.0,0.0,90617.000,90085.0,0,-532.0,-773.0
1,8737.0,1052,822.0,131.0,11.0,2021.0,1.0,3.0,bahrain,0.00,0.0,11.0,20.0,89708.0,1492.0,1200.5,0.0,0.0,91200.000,90186.0,0,-1014.0,-773.0
2,8743.0,1052,4.0,214.0,7.0,2021.0,1.0,3.0,bahrain,0.00,0.0,7.0,20.0,89708.0,1155.0,1585.5,0.0,0.0,90863.000,90595.0,0,-268.0,-134.0
3,8750.0,1052,839.0,214.0,16.0,2021.0,1.0,3.0,bahrain,0.00,0.0,16.0,20.0,89708.0,2016.0,1585.5,0.0,0.0,91724.000,0.0,1,0.0,-134.0
4,8748.0,1052,8.0,51.0,14.0,2021.0,1.0,3.0,bahrain,0.00,0.0,14.0,20.0,89708.0,1839.0,1564.5,0.0,0.0,91547.000,91238.0,0,-309.0,-299.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,9883.0,1111,842.0,214.0,0.0,2024.0,1.0,3.0,bahrain,20.00,0.0,20.0,20.0,89708.0,NaN,NaN,-2473.0,-2136.5,92144.375,NaN,1,NaN,NaN
76,9886.0,1111,846.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,22.5,6.0,15.5,89708.0,NaN,NaN,-1944.0,-2168.5,92071.910,NaN,0,NaN,NaN
77,9878.0,1111,857.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,10.0,16.0,18.0,89708.0,NaN,NaN,-2393.0,-2168.5,92117.370,NaN,1,NaN,NaN
78,9888.0,1111,848.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,55.0,7.0,9.0,89708.0,NaN,NaN,-1753.0,-1848.5,92093.260,NaN,0,NaN,NaN
79,9890.0,1111,858.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,22.5,15.0,15.5,89708.0,NaN,NaN,-1944.0,-1848.5,92116.150,NaN,0,NaN,NaN

In [13]:
df1 = df1.rename(columns={'driver_q2vsq1_x': 'driver_q2vsq1', 'driver_q2vsq1_y': 'car_q2vsq1'})

In [14]:
df1['previous_driver_q2vsq1'] = df1.groupby(['circuitref', 'driverid'])['driver_q2vsq1'].shift()
df1.previous_driver_q2vsq1 = df1.previous_driver_q2vsq1.fillna(0)
df1

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,car_condition,driver_condition,position_q1,previous_year_position_q1,circuitref_fastlap,driver_time_vs_fastlap,car_time_vs_fastlap,previous_driver_time_vs_fastlap,previous_car_time_vs_fastlap,q1,q2,q2disqualified,driver_q2vsq1,car_q2vsq1,previous_driver_q2vsq1
0,8736.0,1052,1.0,131.0,3.0,2021.0,1.0,3.0,bahrain,0.00,0.0,3.0,20.0,89708.0,909.0,1200.5,0.0,0.0,90617.000,90085.0,0,-532.0,-773.0,0.0
1,8737.0,1052,822.0,131.0,11.0,2021.0,1.0,3.0,bahrain,0.00,0.0,11.0,20.0,89708.0,1492.0,1200.5,0.0,0.0,91200.000,90186.0,0,-1014.0,-773.0,0.0
2,8743.0,1052,4.0,214.0,7.0,2021.0,1.0,3.0,bahrain,0.00,0.0,7.0,20.0,89708.0,1155.0,1585.5,0.0,0.0,90863.000,90595.0,0,-268.0,-134.0,0.0
3,8750.0,1052,839.0,214.0,16.0,2021.0,1.0,3.0,bahrain,0.00,0.0,16.0,20.0,89708.0,2016.0,1585.5,0.0,0.0,91724.000,0.0,1,0.0,-134.0,0.0
4,8748.0,1052,8.0,51.0,14.0,2021.0,1.0,3.0,bahrain,0.00,0.0,14.0,20.0,89708.0,1839.0,1564.5,0.0,0.0,91547.000,91238.0,0,-309.0,-299.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,9883.0,1111,842.0,214.0,0.0,2024.0,1.0,3.0,bahrain,20.00,0.0,20.0,20.0,89708.0,NaN,NaN,-2473.0,-2136.5,92144.375,NaN,1,NaN,NaN,0.0
76,9886.0,1111,846.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,22.5,6.0,15.5,89708.0,NaN,NaN,-1944.0,-2168.5,92071.910,NaN,0,NaN,NaN,-271.0
77,9878.0,1111,857.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,10.0,16.0,18.0,89708.0,NaN,NaN,-2393.0,-2168.5,92117.370,NaN,1,NaN,NaN,0.0
78,9888.0,1111,848.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,55.0,7.0,9.0,89708.0,NaN,NaN,-1753.0,-1848.5,92093.260,NaN,0,NaN,NaN,0.0
79,9890.0,1111,858.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,22.5,15.0,15.5,89708.0,NaN,NaN,-1944.0,-1848.5,92116.150,NaN,0,NaN,NaN,0.0

In [15]:
max_q2 = df1['q2'].max()
df1['q2'].replace(0, max_q2, inplace=True)

In [16]:
df1['previous_car_q2vsq1'] = df1.groupby(['circuitref', 'driverid'])['car_q2vsq1'].shift()
df1.previous_car_q2vsq1 = df1.previous_car_q2vsq1.fillna(0)
df1

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,car_condition,driver_condition,position_q1,previous_year_position_q1,circuitref_fastlap,driver_time_vs_fastlap,car_time_vs_fastlap,previous_driver_time_vs_fastlap,previous_car_time_vs_fastlap,q1,q2,q2disqualified,driver_q2vsq1,car_q2vsq1,previous_driver_q2vsq1,previous_car_q2vsq1
0,8736.0,1052,1.0,131.0,3.0,2021.0,1.0,3.0,bahrain,0.00,0.0,3.0,20.0,89708.0,909.0,1200.5,0.0,0.0,90617.000,90085.0,0,-532.0,-773.0,0.0,0.0
1,8737.0,1052,822.0,131.0,11.0,2021.0,1.0,3.0,bahrain,0.00,0.0,11.0,20.0,89708.0,1492.0,1200.5,0.0,0.0,91200.000,90186.0,0,-1014.0,-773.0,0.0,0.0
2,8743.0,1052,4.0,214.0,7.0,2021.0,1.0,3.0,bahrain,0.00,0.0,7.0,20.0,89708.0,1155.0,1585.5,0.0,0.0,90863.000,90595.0,0,-268.0,-134.0,0.0,0.0
3,8750.0,1052,839.0,214.0,16.0,2021.0,1.0,3.0,bahrain,0.00,0.0,16.0,20.0,89708.0,2016.0,1585.5,0.0,0.0,91724.000,93543.0,1,0.0,-134.0,0.0,0.0
4,8748.0,1052,8.0,51.0,14.0,2021.0,1.0,3.0,bahrain,0.00,0.0,14.0,20.0,89708.0,1839.0,1564.5,0.0,0.0,91547.000,91238.0,0,-309.0,-299.5,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,9883.0,1111,842.0,214.0,0.0,2024.0,1.0,3.0,bahrain,20.00,0.0,20.0,20.0,89708.0,NaN,NaN,-2473.0,-2136.5,92144.375,NaN,1,NaN,NaN,0.0,-297.0
76,9886.0,1111,846.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,22.5,6.0,15.5,89708.0,NaN,NaN,-1944.0,-2168.5,92071.910,NaN,0,NaN,NaN,-271.0,-135.5
77,9878.0,1111,857.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,10.0,16.0,18.0,89708.0,NaN,NaN,-2393.0,-2168.5,92117.370,NaN,1,NaN,NaN,0.0,-135.5
78,9888.0,1111,848.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,55.0,7.0,9.0,89708.0,NaN,NaN,-1753.0,-1848.5,92093.260,NaN,0,NaN,NaN,0.0,0.0
79,9890.0,1111,858.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,22.5,15.0,15.5,89708.0,NaN,NaN,-1944.0,-1848.5,92116.150,NaN,0,NaN,NaN,0.0,0.0

In [17]:
df1['position_q2'] = df1.groupby(['circuitref', 'year'])['q2'].rank()
df1

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,car_condition,driver_condition,position_q1,previous_year_position_q1,circuitref_fastlap,driver_time_vs_fastlap,car_time_vs_fastlap,previous_driver_time_vs_fastlap,previous_car_time_vs_fastlap,q1,q2,q2disqualified,driver_q2vsq1,car_q2vsq1,previous_driver_q2vsq1,previous_car_q2vsq1,position_q2
0,8736.0,1052,1.0,131.0,3.0,2021.0,1.0,3.0,bahrain,0.00,0.0,3.0,20.0,89708.0,909.0,1200.5,0.0,0.0,90617.000,90085.0,0,-532.0,-773.0,0.0,0.0,3.0
1,8737.0,1052,822.0,131.0,11.0,2021.0,1.0,3.0,bahrain,0.00,0.0,11.0,20.0,89708.0,1492.0,1200.5,0.0,0.0,91200.000,90186.0,0,-1014.0,-773.0,0.0,0.0,5.0
2,8743.0,1052,4.0,214.0,7.0,2021.0,1.0,3.0,bahrain,0.00,0.0,7.0,20.0,89708.0,1155.0,1585.5,0.0,0.0,90863.000,90595.0,0,-268.0,-134.0,0.0,0.0,9.0
3,8750.0,1052,839.0,214.0,16.0,2021.0,1.0,3.0,bahrain,0.00,0.0,16.0,20.0,89708.0,2016.0,1585.5,0.0,0.0,91724.000,93543.0,1,0.0,-134.0,0.0,0.0,18.0
4,8748.0,1052,8.0,51.0,14.0,2021.0,1.0,3.0,bahrain,0.00,0.0,14.0,20.0,89708.0,1839.0,1564.5,0.0,0.0,91547.000,91238.0,0,-309.0,-299.5,0.0,0.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,9883.0,1111,842.0,214.0,0.0,2024.0,1.0,3.0,bahrain,20.00,0.0,20.0,20.0,89708.0,NaN,NaN,-2473.0,-2136.5,92144.375,NaN,1,NaN,NaN,0.0,-297.0,NaN
76,9886.0,1111,846.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,22.5,6.0,15.5,89708.0,NaN,NaN,-1944.0,-2168.5,92071.910,NaN,0,NaN,NaN,-271.0,-135.5,NaN
77,9878.0,1111,857.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,10.0,16.0,18.0,89708.0,NaN,NaN,-2393.0,-2168.5,92117.370,NaN,1,NaN,NaN,0.0,-135.5,NaN
78,9888.0,1111,848.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,55.0,7.0,9.0,89708.0,NaN,NaN,-1753.0,-1848.5,92093.260,NaN,0,NaN,NaN,0.0,0.0,NaN
79,9890.0,1111,858.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,22.5,15.0,15.5,89708.0,NaN,NaN,-1944.0,-1848.5,92116.150,NaN,0,NaN,NaN,0.0,0.0,NaN

In [18]:
df1['previous_year_position_q2'] = df1.groupby(['circuitref', 'driverid'])['position_q2'].shift()
df1.previous_year_position_q2 = df1.previous_year_position_q2.fillna(20)
df1

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,car_condition,driver_condition,position_q1,previous_year_position_q1,circuitref_fastlap,driver_time_vs_fastlap,car_time_vs_fastlap,previous_driver_time_vs_fastlap,previous_car_time_vs_fastlap,q1,q2,q2disqualified,driver_q2vsq1,car_q2vsq1,previous_driver_q2vsq1,previous_car_q2vsq1,position_q2,previous_year_position_q2
0,8736.0,1052,1.0,131.0,3.0,2021.0,1.0,3.0,bahrain,0.00,0.0,3.0,20.0,89708.0,909.0,1200.5,0.0,0.0,90617.000,90085.0,0,-532.0,-773.0,0.0,0.0,3.0,20.0
1,8737.0,1052,822.0,131.0,11.0,2021.0,1.0,3.0,bahrain,0.00,0.0,11.0,20.0,89708.0,1492.0,1200.5,0.0,0.0,91200.000,90186.0,0,-1014.0,-773.0,0.0,0.0,5.0,20.0
2,8743.0,1052,4.0,214.0,7.0,2021.0,1.0,3.0,bahrain,0.00,0.0,7.0,20.0,89708.0,1155.0,1585.5,0.0,0.0,90863.000,90595.0,0,-268.0,-134.0,0.0,0.0,9.0,20.0
3,8750.0,1052,839.0,214.0,16.0,2021.0,1.0,3.0,bahrain,0.00,0.0,16.0,20.0,89708.0,2016.0,1585.5,0.0,0.0,91724.000,93543.0,1,0.0,-134.0,0.0,0.0,18.0,20.0
4,8748.0,1052,8.0,51.0,14.0,2021.0,1.0,3.0,bahrain,0.00,0.0,14.0,20.0,89708.0,1839.0,1564.5,0.0,0.0,91547.000,91238.0,0,-309.0,-299.5,0.0,0.0,14.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,9883.0,1111,842.0,214.0,0.0,2024.0,1.0,3.0,bahrain,20.00,0.0,20.0,20.0,89708.0,NaN,NaN,-2473.0,-2136.5,92144.375,NaN,1,NaN,NaN,0.0,-297.0,NaN,17.5
76,9886.0,1111,846.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,22.5,6.0,15.5,89708.0,NaN,NaN,-1944.0,-2168.5,92071.910,NaN,0,NaN,NaN,-271.0,-135.5,NaN,11.0
77,9878.0,1111,857.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,10.0,16.0,18.0,89708.0,NaN,NaN,-2393.0,-2168.5,92117.370,NaN,1,NaN,NaN,0.0,-135.5,NaN,17.5
78,9888.0,1111,848.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,55.0,7.0,9.0,89708.0,NaN,NaN,-1753.0,-1848.5,92093.260,NaN,0,NaN,NaN,0.0,0.0,NaN,17.5
79,9890.0,1111,858.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,22.5,15.0,15.5,89708.0,NaN,NaN,-1944.0,-1848.5,92116.150,NaN,0,NaN,NaN,0.0,0.0,NaN,17.5

In [19]:
df1.columns

Index(['qualifyid', 'raceid', 'driverid', 'constructorid', 'position_final',
       'year', 'round', 'circuitid', 'circuitref', 'car_condition',
       'driver_condition', 'position_q1', 'previous_year_position_q1',
       'circuitref_fastlap', 'driver_time_vs_fastlap', 'car_time_vs_fastlap',
       'previous_driver_time_vs_fastlap', 'previous_car_time_vs_fastlap', 'q1',
       'q2', 'q2disqualified', 'driver_q2vsq1', 'car_q2vsq1',
       'previous_driver_q2vsq1', 'previous_car_q2vsq1', 'position_q2',
       'previous_year_position_q2'],
      dtype='object')

In [20]:
column_order = ['qualifyid', 'raceid', 'driverid', 'constructorid', 'position_final',
       'year', 'round', 'circuitid', 'circuitref', 'car_condition',
       'driver_condition', 'position_q1', 'previous_year_position_q1',
       'circuitref_fastlap', 'driver_time_vs_fastlap', 'car_time_vs_fastlap',
       'previous_driver_time_vs_fastlap', 'previous_car_time_vs_fastlap', 
        'q2disqualified', 'driver_q2vsq1', 'car_q2vsq1',
       'previous_driver_q2vsq1', 'previous_car_q2vsq1', 'position_q2',
       'previous_year_position_q2', 'q1', 'q2']
df1 = df1.reindex(columns=column_order)

In [21]:
df1.to_csv('dataframe_trabajar_posiciones_finales.csv', index=False)

In [22]:
dfq2 = df1[df1["q2disqualified"] == 0]

<h1 style="color: #F70206; text-shadow: 2px 2px 4px #000000; border: 1px solid #000000; font-size: 36px;">02 | EDA</h1>

<h1 style="color: #F70206; text-shadow: 2px 2px 4px #000000; border: 1px solid #000000; font-size: 36px;">04 | Modeling</h1>

<h4 style="color: #F70206;">Train-Test Split</h4>

In [23]:
dfq2.isnull().sum()

qualifyid                           0
raceid                              0
driverid                            0
constructorid                       0
position_final                      0
year                                0
round                               0
circuitid                           0
circuitref                          0
car_condition                       0
driver_condition                    0
position_q1                         0
previous_year_position_q1           0
circuitref_fastlap                  0
driver_time_vs_fastlap             15
car_time_vs_fastlap                15
previous_driver_time_vs_fastlap     0
previous_car_time_vs_fastlap        0
q2disqualified                      0
driver_q2vsq1                      15
car_q2vsq1                         15
previous_driver_q2vsq1              0
previous_car_q2vsq1                 0
position_q2                        15
previous_year_position_q2           0
q1                                  0
q2                                 15
dtype: int64

['qualifyid', 'raceid', 'driverid', 'constructorid', 'position', 'year',
       'round', 'circuitid', 'circuitref', 'car_condition', 'driver_condition',
       'previous_year_position', 'circuitref_fastlap',
       'driver_time_vs_fastlap', 'car_time_vs_fastlap',
       'previous_circuitref_fastlap', 'previous_driver_time_vs_fastlap',
       'previous_car_time_vs_fastlap', 'disqualified',
       'driver_q2vsq1', 'car_q2vsq1', 'previous_driver_q2vsq1',
       'previous_car_q2vsq1', 'q1', 'q2']

In [24]:
drop_list = ["q2", "raceid", "position_final", "circuitref", "driver_time_vs_fastlap",
             "car_time_vs_fastlap", "raceid", "car_condition",
            "driver_condition", 'driver_q2vsq1', 'car_q2vsq1',"q1", "position_q2"]

In [25]:
dfq2.tail(30)

,qualifyid,raceid,driverid,constructorid,position_final,year,round,circuitid,circuitref,car_condition,driver_condition,position_q1,previous_year_position_q1,circuitref_fastlap,driver_time_vs_fastlap,car_time_vs_fastlap,previous_driver_time_vs_fastlap,previous_car_time_vs_fastlap,q2disqualified,driver_q2vsq1,car_q2vsq1,previous_driver_q2vsq1,previous_car_q2vsq1,position_q2,previous_year_position_q2,q1,q2
38,9189.0,1074,848.0,3.0,15.0,2022.0,1.0,3.0,bahrain,7.50,0.0,15.0,20.0,89708.0,3018.0,3472.0,0.0,0.0,0,-62.0,-31.0,0.0,0.0,14.0,20.0,92726.000,92664.0
40,9639.0,1098,1.0,131.0,13.0,2023.0,1.0,3.0,bahrain,52.50,50.0,13.0,10.0,89708.0,1835.0,1592.0,-2577.0,-2569.0,0,-1030.0,-790.0,-1237.0,-1127.0,4.0,5.0,91543.000,90513.0
41,9638.0,1098,847.0,131.0,2.0,2023.0,1.0,3.0,bahrain,52.50,55.0,2.0,9.0,89708.0,1349.0,1592.0,-2561.0,-2569.0,0,-550.0,-790.0,-1017.0,-1127.0,3.0,6.0,91057.000,90507.0
42,9637.0,1098,4.0,117.0,4.0,2023.0,1.0,3.0,bahrain,22.50,40.0,4.0,12.0,89708.0,1450.0,1463.0,-2638.0,-2485.5,0,-513.0,-285.0,-725.0,-492.0,6.0,8.0,91158.000,90645.0
43,9640.0,1098,840.0,117.0,5.0,2023.0,1.0,3.0,bahrain,22.50,5.0,5.0,19.0,89708.0,1476.0,1463.0,-3324.0,-3196.5,0,-57.0,-285.0,0.0,0.0,10.0,17.5,91184.000,91127.0
44,9642.0,1098,807.0,210.0,6.0,2023.0,1.0,3.0,bahrain,45.00,15.0,6.0,17.0,89708.0,1496.0,1840.0,-3069.0,-3196.5,0,-395.0,-197.5,0.0,0.0,8.0,17.5,91204.000,90809.0
46,9634.0,1098,815.0,9.0,10.0,2023.0,1.0,3.0,bahrain,65.00,45.0,10.0,11.0,89708.0,1771.0,1679.0,-2603.0,-2340.0,0,-733.0,-762.5,-1303.0,-1165.5,7.0,4.0,91479.000,90746.0
47,9633.0,1098,830.0,9.0,7.0,2023.0,1.0,3.0,bahrain,65.00,85.0,7.0,3.0,89708.0,1587.0,1679.0,-2077.0,-2340.0,0,-792.0,-762.5,-1028.0,-1165.5,2.0,1.0,91295.000,90503.0
48,9644.0,1098,822.0,51.0,11.0,2023.0,1.0,3.0,bahrain,55.00,80.0,11.0,4.0,89708.0,1796.0,1851.5,-2211.0,-2498.0,0,-61.0,-101.5,-202.0,424.0,12.0,10.0,91504.000,91443.0
49,9645.0,1098,855.0,51.0,14.0,2023.0,1.0,3.0,bahrain,55.00,30.0,14.0,14.0,89708.0,1907.0,1851.5,-2785.0,-2498.0,0,-142.0,-101.5,1050.0,424.0,13.0,17.5,91615.000,91473.0
50,9636.0,1098,832.0,6.0,1.0,2023.0,1.0,3.0,bahrain,92.50,90.0,1.0,2.0,89708.0,1285.0,1335.5,-1859.0,-1811.0,0,-478.0,-645.0,-780.0,-659.5,5.0,2.0,90993.000,90515.0
51,9635.0,1098,844.0,6.0,3.0,2023.0,1.0,3.0,bahrain,92.50,95.0,3.0,1.0,89708.0,1386.0,1335.5,-1763.0,-1811.0,0,-812.0,-645.0,-539.0,-659.5,1.0,3.0,91094.000,90282.0
52,9641.0,1098,839.0,214.0,12.0,2023.0,1.0,3.0,bahrain,67.50,70.0,12.0,6.0,89708.0,1800.0,2136.5,-2333.0,-2485.5,0,-594.0,-297.0,-259.0,-492.0,9.0,11.0,91508.000,90914.0
56,9647.0,1098,848.0,3.0,9.0,2023.0,1.0,3.0,bahrain,12.50,25.0,9.0,15.0,89708.0,1753.0,1848.5,-3018.0,-3472.0,0,0.0,0.0,-62.0,-31.0,17.5,14.0,91461.000,93543.0
58,9646.0,1098,852.0,213.0,8.0,2023.0,1.0,3.0,bahrain,10.00,20.0,8.0,16.0,89708.0,1692.0,2052.5,-3042.0,-2715.0,0,1110.0,555.0,0.0,-230.5,14.0,17.5,91400.000,92510.0
60,9875.0,1111,1.0,131.0,0.0,2024.0,1.0,3.0,bahrain,62.50,35.0,4.0,13.0,89708.0,NaN,NaN,-1835.0,-1592.0,0,NaN,NaN,-1030.0,-790.0,NaN,4.0,92058.875,NaN
62,9877.0,1111,4.0,117.0,0.0,2024.0,1.0,3.0,bahrain,77.50,80.0,9.0,4.0,89708.0,NaN,NaN,-1450.0,-1463.0,0,NaN,NaN,-513.0,-285.0,NaN,6.0,92100.700,NaN
63,9885.0,1111,840.0,117.0,0.0,2024.0,1.0,3.0,bahrain,77.50,75.0,14.0,5.0,89708.0,NaN,NaN,-1476.0,-1463.0,0,NaN,NaN,-57.0,-285.0,NaN,10.0,92114.820,NaN
64,9892.0,1111,807.0,213.0,0.0,2024.0,1.0,3.0,bahrain,70.00,70.0,13.0,6.0,89708.0,NaN,NaN,-1496.0,-1840.0,0,NaN,NaN,-395.0,-197.5,NaN,8.0,92113.950,NaN
65,9891.0,1111,817.0,213.0,0.0,2024.0,1.0,3.0,bahrain,70.00,10.0,1.0,18.0,89708.0,NaN,NaN,-3237.0,-2884.0,0,NaN,NaN,0.0,-115.5,NaN,17.5,92049.450,NaN
66,9881.0,1111,852.0,213.0,0.0,2024.0,1.0,3.0,bahrain,70.00,60.0,10.0,8.0,89708.0,NaN,NaN,-1692.0,-2052.5,0,NaN,NaN,1110.0,555.0,NaN,14.0,92103.460,NaN
67,9879.0,1111,815.0,9.0,0.0,2024.0,1.0,3.0,bahrain,57.50,50.0,3.0,10.0,89708.0,NaN,NaN,-1771.0,-1679.0,0,NaN,NaN,-733.0,-762.5,NaN,7.0,92055.970,NaN
69,9882.0,1111,822.0,51.0,0.0,2024.0,1.0,3.0,bahrain,37.50,45.0,2.0,11.0,89708.0,NaN,NaN,-1796.0,-1851.5,0,NaN,NaN,-61.0,-101.5,NaN,12.0,92052.820,NaN
70,9889.0,1111,855.0,51.0,0.0,2024.0,1.0,3.0,bahrain,37.50,30.0,8.0,14.0,89708.0,NaN,NaN,-1907.0,-1851.5,0,NaN,NaN,-142.0,-101.5,NaN,13.0,92098.150,NaN
71,9887.0,1111,825.0,210.0,0.0,2024.0,1.0,3.0,bahrain,7.50,15.0,5.0,17.0,89708.0,NaN,NaN,-2184.0,-1840.0,0,NaN,NaN,0.0,-197.5,NaN,17.5,92071.500,NaN
72,9876.0,1111,832.0,6.0,0.0,2024.0,1.0,3.0,bahrain,90.00,95.0,12.0,1.0,89708.0,NaN,NaN,-1285.0,-1335.5,0,NaN,NaN,-478.0,-645.0,NaN,5.0,92108.460,NaN
73,9873.0,1111,844.0,6.0,0.0,2024.0,1.0,3.0,bahrain,90.00,85.0,11.0,3.0,89708.0,NaN,NaN,-1386.0,-1335.5,0,NaN,NaN,-812.0,-645.0,NaN,1.0,92106.610,NaN
76,9886.0,1111,846.0,1.0,0.0,2024.0,1.0,3.0,bahrain,16.25,22.5,6.0,15.5,89708.0,NaN,NaN,-1944.0,-2168.5,0,NaN,NaN,-271.0,-135.5,NaN,11.0,92071.910,NaN
78,9888.0,1111,848.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,55.0,7.0,9.0,89708.0,NaN,NaN,-1753.0,-1848.5,0,NaN,NaN,0.0,0.0,NaN,17.5,92093.260,NaN
79,9890.0,1111,858.0,3.0,0.0,2024.0,1.0,3.0,bahrain,38.75,22.5,15.0,15.5,89708.0,NaN,NaN,-1944.0,-1848.5,0,NaN,NaN,0.0,0.0,NaN,17.5,92116.150,NaN

df1_bahrain  , 'yeda', 'albert_park', 'suzuka', 'shanghai', 'miami',
       'imola', 'monaco', 'villeneuve', 'catalunya', 'red_bull_ring',
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [26]:
    X = dfq2.drop(drop_list, axis=1)
    y = dfq2["q2"]
    X_2024 = X[dfq2['year'] == 2024]
    y_2024 = y[dfq2['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[dfq2['year'] != 2024], 
                                                        y[dfq2['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(dfq2)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')
    
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
    df_bahrain_2024 = pd.concat([series_pred_2024.reset_index(drop=True), 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

100% of our data: 59.
80% for training data: 43.
20% for test data: 1.

,overall,predictions_test,predictions_real_xgb,predictions_real_linearregresion,predictions_real_ridge,predictions_real_lasso,predictions_real_tree,predictions_real_knn
0,90513.0,90941.664062,91217.257812,87422.584160,91877.314923,91896.073851,90746.0,90732.4
1,NaN,NaN,91342.562500,87298.318656,91793.556181,91809.563925,90746.0,90894.8
2,NaN,NaN,91430.367188,87929.287351,92297.560911,92312.731746,91443.0,91044.4
3,NaN,NaN,91526.070312,88723.881742,92906.589480,92923.122457,91443.0,90900.2
4,NaN,NaN,91141.851562,87030.548566,91326.182473,91340.454227,90809.0,91997.4
5,NaN,NaN,91725.453125,88043.258790,92480.953649,92497.820660,91473.0,91372.8
6,NaN,NaN,90982.156250,87156.527463,91581.582903,91597.643640,90746.0,91005.0
7,NaN,NaN,91412.562500,87207.029056,91629.706797,91645.201084,90809.0,90987.2
8,NaN,NaN,92012.085938,87991.057904,92307.705617,92324.003150,90507.0,90987.2
9,NaN,NaN,91510.804688,87433.132371,91804.628909,91819.847576,90809.0,90987.2
10,NaN,NaN,91030.460938,87422.552850,91929.694770,91944.937732,90746.0,91106.0
11,NaN,NaN,90920.242188,87840.830559,92346.065234,92363.764765,90282.0,91106.0
12,NaN,NaN,92027.093750,88156.477881,92507.057920,92524.871970,91127.0,90987.2
13,NaN,NaN,92364.835938,87051.272982,91499.240892,91511.627074,90507.0,90987.2
14,NaN,NaN,92818.804688,88228.790891,92648.098762,92663.718477,92664.0,90987.2

In [27]:
df_bahrain_2024['position_xgb'] = df_bahrain_2024['predictions_real_xgb'].rank(method='min')
df_bahrain_2024['position_linearregresion'] = df_bahrain_2024['predictions_real_linearregresion'].rank(method='min')
df_bahrain_2024['position_ridge'] = df_bahrain_2024['predictions_real_ridge'].rank(method='min')
df_bahrain_2024['position_lasso'] = df_bahrain_2024['predictions_real_lasso'].rank(method='min')
df_bahrain_2024['position_tree'] = df_bahrain_2024['predictions_real_tree'].rank(method='min')
df_bahrain_2024['position_knn'] = df_bahrain_2024['predictions_real_knn'].rank(method='min')

In [28]:
df_bahrain_2024

,predictions_real_xgb,predictions_real_linearregresion,predictions_real_ridge,predictions_real_lasso,predictions_real_tree,predictions_real_knn,position_xgb,position_linearregresion,position_ridge,position_lasso,position_tree,position_knn
0,91217.257812,87422.584160,91877.314923,91896.073851,90746.0,90732.4,5.0,7.0,7.0,7.0,4.0,1.0
1,91342.562500,87298.318656,91793.556181,91809.563925,90746.0,90894.8,6.0,5.0,5.0,5.0,4.0,2.0
2,91430.367188,87929.287351,92297.560911,92312.731746,91443.0,91044.4,8.0,10.0,9.0,9.0,12.0,11.0
3,91526.070312,88723.881742,92906.589480,92923.122457,91443.0,90900.2,10.0,15.0,15.0,15.0,12.0,3.0
4,91141.851562,87030.548566,91326.182473,91340.454227,90809.0,91997.4,4.0,1.0,1.0,1.0,8.0,15.0
5,91725.453125,88043.258790,92480.953649,92497.820660,91473.0,91372.8,11.0,12.0,12.0,12.0,14.0,14.0
6,90982.156250,87156.527463,91581.582903,91597.643640,90746.0,91005.0,2.0,3.0,3.0,3.0,4.0,10.0
7,91412.562500,87207.029056,91629.706797,91645.201084,90809.0,90987.2,7.0,4.0,4.0,4.0,8.0,4.0
8,92012.085938,87991.057904,92307.705617,92324.003150,90507.0,90987.2,12.0,11.0,10.0,10.0,2.0,4.0
9,91510.804688,87433.132371,91804.628909,91819.847576,90809.0,90987.2,9.0,8.0,6.0,6.0,8.0,4.0
10,91030.460938,87422.552850,91929.694770,91944.937732,90746.0,91106.0,3.0,6.0,8.0,8.0,4.0,12.0
11,90920.242188,87840.830559,92346.065234,92363.764765,90282.0,91106.0,1.0,9.0,11.0,11.0,1.0,12.0
12,92027.093750,88156.477881,92507.057920,92524.871970,91127.0,90987.2,13.0,13.0,13.0,13.0,11.0,4.0
13,92364.835938,87051.272982,91499.240892,91511.627074,90507.0,90987.2,14.0,2.0,2.0,2.0,2.0,4.0
14,92818.804688,88228.790891,92648.098762,92663.718477,92664.0,90987.2,15.0,14.0,14.0,14.0,15.0,4.0

In [29]:
df_bahrain_2024.to_csv('dfq2_bahrain_2024.csv', index=False)

In [30]:
dfq2.to_csv('dfq2_bahrain.csv', index=False)

df1_yeda  , 'yeda', 'albert_park', 'suzuka', 'shanghai', 'miami',
       'imola', 'monaco', 'villeneuve', 'catalunya', 'red_bull_ring',
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [31]:
    X = df1_yeda.drop(drop_list, axis=1)
    y = df1_yeda["q1"]
    X_2024 = X[df1_yeda['year'] == 2024]
    y_2024 = y[df1_yeda['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_yeda['year'] != 2024], 
                                                        y[df1_yeda['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_yeda)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

NameError: name 'df1_yeda' is not defined

df1_albert_park  , 'albert_park', 'suzuka', 'shanghai', 'miami',
       'imola', 'monaco', 'villeneuve', 'catalunya', 'red_bull_ring',
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_albert_park.drop(drop_list, axis=1)
    y = df1_albert_park["q1"]
    X_2024 = X[df1_albert_park['year'] == 2024]
    y_2024 = y[df1_albert_park['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_albert_park['year'] != 2024], 
                                                        y[df1_albert_park['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_albert_park)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_suzuka , 'suzuka', 'shanghai', 'miami',
       'imola', 'monaco', 'villeneuve', 'catalunya', 'red_bull_ring',
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_suzuka.drop(drop_list, axis=1)
    y = df1_suzuka["q1"]
    X_2024 = X[df1_suzuka['year'] == 2024]
    y_2024 = y[df1_suzuka['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_suzuka['year'] != 2024], 
                                                        y[df1_suzuka['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_suzuka)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_shanghai ,, 'shanghai', 'miami',
       'imola', 'monaco', 'villeneuve', 'catalunya', 'red_bull_ring',
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_shanghai.drop(drop_list, axis=1)
    y = df1_shanghai["q1"]
    X_2024 = X[df1_shanghai['year'] == 2024]
    y_2024 = y[df1_shanghai['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_shanghai['year'] != 2024], 
                                                        y[df1_shanghai['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_miami ,, , 'miami',
       'imola', 'monaco', 'villeneuve', 'catalunya', 'red_bull_ring',
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_miami.drop(drop_list, axis=1)
    y = df1_miami["q1"]
    X_2024 = X[df1_miami['year'] == 2024]
    y_2024 = y[df1_miami['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_miami['year'] != 2024], 
                                                        y[df1_miami['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_miami)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_imola 
       'imola', 'monaco', 'villeneuve', 'catalunya', 'red_bull_ring',
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_imola.drop(drop_list, axis=1)
    y = df1_imola["q1"]
    X_2024 = X[df1_imola['year'] == 2024]
    y_2024 = y[df1_imola['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_imola['year'] != 2024], 
                                                        y[df1_imola['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_imola)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_monaco 
       , 'monaco', 'villeneuve', 'catalunya', 'red_bull_ring',
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_monaco.drop(drop_list, axis=1)
    y = df1_monaco["q1"]
    X_2024 = X[df1_monaco['year'] == 2024]
    y_2024 = y[df1_monaco['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_monaco['year'] != 2024], 
                                                        y[df1_monaco['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_monaco)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

In [ ]:
df1_villeneuve[df1_villeneuve['year'] == 2024]

df1_villeneuve

In [ ]:
    X = df1_villeneuve.drop(drop_list, axis=1)
    y = df1_villeneuve["q1"]
    X_2024 = X[df1_villeneuve['year'] == 2024]
    y_2024 = y[df1_villeneuve['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_villeneuve['year'] != 2024], 
                                                        y[df1_villeneuve['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_villeneuve)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_catalunya
       ,  'catalunya', 'red_bull_ring',
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_catalunya.drop(drop_list, axis=1)
    y = df1_catalunya["q1"]
    X_2024 = X[df1_catalunya['year'] == 2024]
    y_2024 = y[df1_catalunya['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_catalunya['year'] != 2024], 
                                                        y[df1_catalunya['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_catalunya)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_red_bull_ring
       ,', 'red_bull_ring',
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_red_bull_ring.drop(drop_list, axis=1)
    y = df1_red_bull_ring["q1"]
    X_2024 = X[df1_red_bull_ring['year'] == 2024]
    y_2024 = y[df1_red_bull_ring['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_red_bull_ring['year'] != 2024], 
                                                        y[df1_red_bull_ring['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_red_bull_ring)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_silverstone
       ,
       'silverstone', 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_silverstone.drop(drop_list, axis=1)
    y = df1_silverstone["q1"]
    X_2024 = X[df1_silverstone['year'] == 2024]
    y_2024 = y[df1_silverstone['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_silverstone['year'] != 2024], 
                                                        y[df1_silverstone['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_silverstone)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_hungaroring
       ,
       , 'hungaroring', 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_hungaroring.drop(drop_list, axis=1)
    y = df1_hungaroring["q1"]
    X_2024 = X[df1_hungaroring['year'] == 2024]
    y_2024 = y[df1_hungaroring['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_hungaroring['year'] != 2024], 
                                                        y[df1_hungaroring['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_hungaroring)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_spa
       ,
       , 'spa', 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_spa.drop(drop_list, axis=1)
    y = df1_spa["q1"]
    X_2024 = X[df1_spa['year'] == 2024]
    y_2024 = y[df1_spa['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_spa['year'] != 2024], 
                                                        y[df1_spa['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_spa)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_zandvoort
       ,
       , 'zandvoort', 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_zandvoort.drop(drop_list, axis=1)
    y = df1_zandvoort["q1"]
    X_2024 = X[df1_zandvoort['year'] == 2024]
    y_2024 = y[df1_zandvoort['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_zandvoort['year'] != 2024], 
                                                        y[df1_zandvoort['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_zandvoort)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_monza
       ,
       ,, 'monza', 'baku',
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_monza.drop(drop_list, axis=1)
    y = df1_monza["q1"]
    X_2024 = X[df1_monza['year'] == 2024]
    y_2024 = y[df1_monza['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_monza['year'] != 2024], 
                                                        y[df1_monza['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_monza)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_baku
 
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_baku.drop(drop_list, axis=1)
    y = df1_baku["q1"]
    X_2024 = X[df1_baku['year'] == 2024]
    y_2024 = y[df1_baku['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_baku['year'] != 2024], 
                                                        y[df1_baku['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_baku)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_marina_bay
 
       'marina_bay', 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_marina_bay.drop(drop_list, axis=1)
    y = df1_marina_bay["q1"]
    X_2024 = X[df1_marina_bay['year'] == 2024]
    y_2024 = y[df1_marina_bay['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_marina_bay['year'] != 2024], 
                                                        y[df1_marina_bay['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_marina_bay)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_americas
 
       , 'americas', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_americas.drop(drop_list, axis=1)
    y = df1_americas["q1"]
    X_2024 = X[df1_americas['year'] == 2024]
    y_2024 = y[df1_americas['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_americas['year'] != 2024], 
                                                        y[df1_americas['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_americas)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_rodriguez
 
       ', 'rodriguez', 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_rodriguez.drop(drop_list, axis=1)
    y = df1_rodriguez["q1"]
    X_2024 = X[df1_rodriguez['year'] == 2024]
    y_2024 = y[df1_rodriguez['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_rodriguez['year'] != 2024], 
                                                        y[df1_rodriguez['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_rodriguez)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_interlagos
 , 'interlagos', 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_interlagos.drop(drop_list, axis=1)
    y = df1_interlagos["q1"]
    X_2024 = X[df1_interlagos['year'] == 2024]
    y_2024 = y[df1_interlagos['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_interlagos['year'] != 2024], 
                                                        y[df1_interlagos['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_interlagos)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

df1_vegas
 ,, 'vegas',
       'losail', 'yas_marina'

In [ ]:
    X = df1_vegas.drop(drop_list, axis=1)
    y = df1_vegas["q1"]
    X_2024 = X[df1_vegas['year'] == 2024]
    y_2024 = y[df1_vegas['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_vegas['year'] != 2024], 
                                                        y[df1_vegas['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_vegas)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

In [ ]:
df1_losail

In [ ]:
    X = df1_losail.drop(drop_list, axis=1)
    y = df1_losail["q1"]
    X_2024 = X[df1_losail['year'] == 2024]
    y_2024 = y[df1_losail['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_losail['year'] != 2024], 
                                                        y[df1_losail['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_losail)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

In [ ]:
df1_yas_marina

In [ ]:
    X = df1_yas_marina.drop(drop_list, axis=1)
    y = df1_yas_marina["q1"]
    X_2024 = X[df1_yas_marina['year'] == 2024]
    y_2024 = y[df1_yas_marina['year'] == 2024]
    X_train, X_test, y_train, y_test = train_test_split(X[df1_yas_marina['year'] != 2024], 
                                                        y[df1_yas_marina['year'] != 2024], 
                                                        test_size=0.02, 
                                                        random_state=0)
    print(f'100% of our data: {len(df1_yas_marina)}.')
    print(f'80% for training data: {len(X_train)}.')
    print(f'20% for test data: {len(X_test)}.')

 
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    predictions_linear_2024  = model.predict(X_2024)
    series_pred_2024_1 = pd.Series(predictions_linear_2024, name='predictions_real_linearregresion')
    
    r2_3 = r2_score(y_test, predictions)
    RMSE_3 = mean_squared_error(y_test, predictions, squared=False)
    MSE_3 = mean_squared_error(y_test, predictions)
    MAE_3 = mean_absolute_error(y_test, predictions)
    
    ridge = Ridge()
    ridge.fit(X_train, y_train)
    predictions_ridge = ridge.predict(X_test)
    predictions_ridge_2024 = ridge.predict(X_2024)
    series_pred_2024_2 = pd.Series(predictions_ridge_2024, name='predictions_real_ridge')
  
    r2_3_2 = r2_score(y_test, predictions_ridge)
    RMSE_3_2 = mean_squared_error(y_test, predictions_ridge, squared=False)
    MSE_3_2 = mean_squared_error(y_test, predictions_ridge)
    MAE_3_2 = mean_absolute_error(y_test, predictions_ridge)
    
    lasso = Lasso()
    lasso.fit(X_train, y_train)
    predictions_lasso = lasso.predict(X_test)
    predictions_lasso_2024 = lasso.predict(X_2024)
    series_pred_2024_3 = pd.Series(predictions_lasso_2024, name='predictions_real_lasso')

    r2_3_3 = r2_score(y_test, predictions_lasso)
    RMSE_3_3 = mean_squared_error(y_test, predictions_lasso, squared=False)
    MSE_3_3 = mean_squared_error(y_test, predictions_lasso)
    MAE_3_3 = mean_absolute_error(y_test, predictions_lasso)
    
    tree = DecisionTreeRegressor()
    tree.fit(X_train, y_train)
    predictions_tree = tree.predict(X_test)
    predictions_tree_2024 = tree.predict(X_2024)
    series_pred_2024_4 = pd.Series(predictions_tree_2024, name='predictions_real_tree')

    r2_3_4 = r2_score(y_test, predictions_tree)
    RMSE_3_4 = mean_squared_error(y_test, predictions_tree, squared=False)
    MSE_3_4 = mean_squared_error(y_test, predictions_tree)
    MAE_3_4 = mean_absolute_error(y_test, predictions_tree)
    
    knn = KNeighborsRegressor()
    knn.fit(X_train, y_train)
    predictions_knn = knn.predict(X_test)
    predictions_knn_2024 = knn.predict(X_2024)
    series_pred_2024_5 = pd.Series(predictions_knn_2024, name='predictions_real_knn')

    r2_3_5 = r2_score(y_test, predictions_knn)
    RMSE_3_5 = mean_squared_error(y_test, predictions_knn, squared=False)
    MSE_3_5 = mean_squared_error(y_test, predictions_knn)
    MAE_3_5 = mean_absolute_error(y_test, predictions_knn)
    
    xgbr = xgb.XGBRFRegressor()
    xgbr.fit(X_train, y_train)
    predictions_xgb = xgbr.predict(X_test)
    predictions_xgb_2024  = xgbr.predict(X_2024)

    r2_3_6 = r2_score(y_test, predictions_xgb)
    RMSE_3_6 = mean_squared_error(y_test, predictions_xgb, squared=False)
    MSE_3_6 = mean_squared_error(y_test, predictions_xgb)
    MAE_3_6 = mean_absolute_error(y_test, predictions_xgb)

    series_pred = pd.Series(predictions_xgb, name='predictions_test')
    series_y_test = pd.Series(y_test, name='overall')
    series_pred_2024 = pd.Series(predictions_xgb_2024, name='predictions_real_xgb')
    comparison_df = pd.concat([series_y_test.reset_index(drop=True), series_pred, series_pred_2024, 
                               series_pred_2024_1, series_pred_2024_2, series_pred_2024_3, 
                              series_pred_2024_4, series_pred_2024_5], axis=1)
comparison_df

<h4 style="color: #F70206;">Selecting the Model: Linear Regression, Model Validation, Metrics</h4>

<h4 style="color: #F70206;">Comparing models: Ridge Regression, XGBoost Regression, KNN Regression, Decision Tree Regression,  Ridge Regression</h4>

<h4 style="color: #F70206;">Columnas categoricas y numericas</h4>

<h4 style="color: #F70206;">Columnas categoricas y numericas</h4>

<h4 style="color: #F70206;">Columnas categoricas y numericas</h4>

<h1 style="color: #F70206; text-shadow: 2px 2px 4px #000000; border: 1px solid #000000; font-size: 36px;">05 | Improving the Model</h1>